templates:

    global:
        if:
        # Make there's 50GB free before adding more downloads
        free_space:
            path: 'D:'
            space: 50000
        # Make sure all filenames are Windows safe (for samba)
        pathscrub: windows
        # Most of these are the results of problem torrents I kept seeing still pop up, so I wholesale blocked them
        # RegExr (http://www.gskinner.com/RegExr/) is a great tool for testing regexes
        regexp:
            reject:
                # Block any subbed/dubbed/etc videos
                - (s|d)ub(s|bed)?\b: {from: title}
                # Spanish releases kept cropping up
                - \bspanish\b: {from: title}
                # Block series, only accept one at a time
                - \b(duo|tri|quadri|tetra|penta)logy\b: {from: title}
                # I don't have any 3D displays
                - \b3-?D\b: {from: title}
                # I've gotten a few trailers that matched as movies. VERY annoying
                - \btrailer\b: {from: title}
                - \bR5\b: {from: title}
                # The following are poor quality types that somehow got through the quality
                - \bWEBSCR\b: {from: title}
                # features usually due to the title including a keyword like "720p" as well
                - \bscreener\b: {from: title}
                - \bTS\b: {from: title}
                - \bCam\b: {from: title}
                - '{C_P}': {from: title}
                # The following are groups with poor quality releases
                - TrTd TeaM: {from: title}
                - \[TNTVillage\]: {from: title}
                - \[facepalm\]: {from: title}
                - \bASAP\b: {from: title}
                # The following are titles that caused me issues from plugins
                - the.day.of.the.doctor
        #Require at least 10 seeds of any torrent
        torrent_alive:
            min_seeds: 10
            reject_for: 1 day
        #Filter by filenames. Allow multiple video types and rar packs 
        #(but note if there is just a single .rar file it won't be accepted)
        content_filter:
            require:
                - '*.avi'
                - '*.mkv'
                - '*.mpg'
                - '*.mp4'
                - '*.r0*'
                - '*.part0*'
            reject:
                - 'password.txt'
                - '*.wmv'
        #Limit the frequency of requests to domains so they don't complain about using a bot
        domain_delay:
            www.torrentleech.org: 10 seconds
            rss.torrentleech.org: 10 minutes
            bt-chat.com: 5 seconds
            thexem.de: 10 seconds
        # The Pirate Bay ssl certs always fail
        verify_ssl_certificates: no
        # Size and seed restrictions require real torrents
        magnets: no
        #slack:
        #    webhook-url: '{{ secrets.slack.webhook_url }}'
        #    text: >
        #        {{task}} - Download started:
        #        {%- if series_name is defined %}
        #        {% set info_string = tvdb_series_name|d(series_name) ~ ' - ' ~ series_id ~ (' - ' ~ tvdb_ep_name if tvdb_ep_name|default(False) else '') %}
        #        {%- if trakt_series_slug is defined and trakt_season is defined and trakt_episode is defined -%}
        #        <https://trakt.tv/shows/{{ trakt_series_slug }}/seasons/{{ trakt_season }}/episodes/{{ trakt_episode }}|{{ info_string }}>
        #        {%- else %}
        #        {{ info_string }}
        #        {%- endif %}
        #       - {{quality}}
        #        {%- elif imdb_name is defined %}
        #       {%- if imdb_url is defined %}
        #        <{{imdb_url}}|{{imdb_name}} {{imdb_year}}>
        #        {%- else %}
        #        {{imdb_name}} {{imdb_year}}
        #        {%- endif %}
        #        - {{quality}}
        #        {%- else -%}
        #        {{title}}
        #        {%- endif %}

#######################################################################################    
    # This template is a "global" template for all TV-related tasks.
    # We keep all of the RSS feeds that list tv-related torrents here
    # as well as where to check existing shows.
    tv:
        # enable information lookups to properly name episodes, extra info, etc.
        thetvdb_lookup: yes
        metainfo_series: yes
        trakt_lookup: yes
        imdb_lookup: yes
        require_field: [series_name, series_id]
        
        #accept or reject content of certain file types
        content_filter:
            #rejection file type list
            reject:
                - '*.rar'
                - '*.zip'
                - '*.wmv'
                - '*.avi'
                
        #not sure what this if category does or what it's filtering
        #or more to the point - how it's filtering and what the impact is
        #if:
        #    - "has_field('category')":
        #        regexp:
        #            reject_excluding:
        #                - '^Episodes( HD)?$': {from: category}
        #archive: [tv]
        
        #impost reasonable file constraints
        content_size:
            max: 5000
            min: 50
        
        #the series plugin!  lots of stuff under here
        #need to learn a lot more about this plugih to see what else it can do
        #and what I can make it do better
        series:
            settings:
                tv:
                    #exact: yes
                    #propers: 3 days
                    upgrade: yes
                    #tracking: no
                    quality: 720p+
            #accept_all: yes
            disable:
                - retry_failed
            #    - seen
                - seen_info_hash
            #seen:
            #    local: yes
            #    fields: 
            #        - title
            #        - url
            #        - original_url
            
            #list of shows watching
            tv:
                - Arrow
                - Blindspot
                - DCs Legends of Tomorrow
                - Designated Survivor
                - Elementary
                - Frequency
                - Lethal Weapon
                #lethal weapon TVDB ID:    311790
                #- tvdb_id: 311790
                - Lucifer
                - Marvels Agents of S H I E L D
                - No Tomorrow
                - Suits
                - Supergirl
                - The Flash
                #- The Flash 2014
                - The Great Indoors
                - Timeless
                - Westworld
                - Wynonna Earp
                - Brooklyn Nine-Nine
                - Gotham
                - Game of Thromes
                - Shameless
                - Smackdown
                - WWE Smackdown
                - Raw
                - WWE Raw
        #deluge: no
        add_trackers:
            - 'udp://tracker.ilibr.org:6969/announce'
            - 'udp://tracker.ilibr.org:80/announce'
            - 'udp://tracker.coppersurfer.tk:6969/announce'
            - 'udp://tracker.coppersurfer.tk:696'
            - 'udp://tracker.opentrackr.org:1337/announce'
            - 'udp://tracker.zer0day.to:1337/announce'
            - 'udp://tracker.leechers-paradise.org:6969'
            - 'udp://tracker.leechers-paradise.org:6969/announce'
            - 'udp://9.rarbg.me:2710/announce'
            - 'udp://p4p.arenabg.ch:1337/announce'
            - 'udp://p4p.arenabg.com:1337/announce'
            - 'udp://9.rarbg.to:2710/announce'
            - 'udp://explodie.org:6969/announce'
            - 'udp://shadowshq.yi.org:6969/announce'
            - 'udp://eddie4.nl:6969/announce'
        
        
        transmission:
            enabled: yes
            host: localhost
            port: 9092
            username: 
            password: 
            magnetization_timeout: 25
            #addpaused: yes
            path: 'D:\TV\Airing\{{ series_name }}\Season 0{{ series_season }}'
            main_file_only: yes
            include_subs: yes
            #main_file_ratio: 2.5
            
            #file types to skip
            skip_files:
                - '*.nfo'
                - '*.sfv'
                - '*[sS]ample*'
                - '*.txt'
                - '*.jpeg'
                - '*.jpg'
            #file types that we want to include
            include_files:
             - '*.srt'
             - '*.sub'
             - '*.idx'
             - '*.ass'
             - '*.ssa'
             
             
             
        #FUNCTION:    Autodeletes torrents once completed
        #don't think that we currently want to do this
        #clean_transmission:
            #enabled: yes
            #host: localhost
            #port: 9092
            #username: 
            #password: 
            #transmission_seed_limits: yes
            
            

#separate tasks for each tracker that we want to parse
#each tracker is fed the same list of programs,
#each from the "tv" template created above
tasks:
    #EZTV.it tracker
    eztv:
        priority: 1
        rss:
            url: https://eztv.ag/ezrss.xml
            link: 
             - torrent:magnetURI
             - link
            ascii: yes
        template: tv
        seen:
            local: yes
            fields: [title, url, original_url]
    #ExtraTorrent.cc
    #also actually called ettv?    who knew!?    
    etcc:
        priority: 2
        rss:
            url: 'https://extratorrent.cc/rss.xml?type=today&cid=8'
            #link: torrent:magnetURI
            ascii: yes
        template: tv
        seen:
            local: yes
            fields: [title, url, original_url]
    #custom showrss.info feed
    showrss:
        priority: 3
        rss:
            url: 'http://showrss.info/user/112448.rss?magnets=true&namespaces=true&name=null&quality=null&re=null'
            #link: magnet
            ascii: yes
        template: tv
        seen:
            local: yes
            fields: [title, url, original_url]
     #TPB - RSS broken there for some time apparently :C
#    tpb:
#        priority: 4
#        rss:
#            url: 'https://thepiratebay.org/rss/new/208'
#            link: magnetURI
#            ascii: yes
#        template: tv
     #kickass torrents - gone, but not forgotten
#    kat:
#        priority: 5
#        rss:
#            url: 'http://kickass.to/search/ettv/?rss=1'
# kat uses a funky cdata object for magnets...
#            link: torrent:magnetURI
#            ascii: yes
#        template: tv


#what time(s) that we want each thing to run at to get shows as fast as possible
schedules:
    # Run at first 10 minutes of each hour starting at 7pm
    - tasks: [eztv, etcc]
        schedule:
            minute: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,42,43,44,45,46,47
            hour: 19,20,21,22,23,00,01
            #day_of_week: mon,tue,wed,thu,sun
    - tasks: [eztv, etcc]
        schedule:
            minute: 2,3,4,5,6,7,8,9,10,45,46,53,54,55
            hour: 02,03,04,05,06,07,08,09,10,11,12,13,14,15,16,17,18
# Run every task once an hour
#    - tasks: '*'
#        interval:
#            hours: 1
    # Run every 30 minutes
#    - tasks: eztv
#        interval:
#            minutes: 30
